INFO 2025-10-17 16:09:12,104 autoreload Watching for file changes with StatReloader
INFO 2025-10-17 16:36:36,537 autoreload Watching for file changes with StatReloader
ERROR 2025-10-17 16:36:39,655 log Internal Server Error: /api/controller-panel/add-user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 56, in _view_wrapper
    test_pass = test_func(request.user)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 79, in <lambda>
    lambda u: u.is_authenticated,
              ^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:39,659 basehttp "GET /api/controller-panel/add-user/ HTTP/1.1" 500 174789
ERROR 2025-10-17 16:36:46,594 log Internal Server Error: /api/controller-panel/add-user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 56, in _view_wrapper
    test_pass = test_func(request.user)
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/decorators.py", line 79, in <lambda>
    lambda u: u.is_authenticated,
              ^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:46,596 basehttp "GET /api/controller-panel/add-user/ HTTP/1.1" 500 174789
ERROR 2025-10-17 16:36:48,804 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:48,806 basehttp "GET /admin/main/user/?q= HTTP/1.1" 500 194526
ERROR 2025-10-17 16:36:54,828 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:54,831 basehttp "GET /admin/main/user/?q=ilxom HTTP/1.1" 500 194634
ERROR 2025-10-17 16:36:55,652 log Internal Server Error: /admin/main/user/189/change/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:55,653 basehttp "GET /admin/main/user/189/change/?_changelist_filters=q%3Dilxom HTTP/1.1" 500 195335
ERROR 2025-10-17 16:36:56,268 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:56,270 basehttp "GET /admin/main/user/?q=ilxom HTTP/1.1" 500 194602
ERROR 2025-10-17 16:36:56,818 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:36:56,819 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 500 194608
ERROR 2025-10-17 16:37:44,283 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:37:44,284 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 500 194608
ERROR 2025-10-17 16:37:45,898 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:37:45,899 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 500 194608
ERROR 2025-10-17 16:37:46,118 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:37:46,119 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 500 194608
ERROR 2025-10-17 16:37:46,303 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:37:46,304 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 500 194608
ERROR 2025-10-17 16:37:46,463 log Internal Server Error: /admin/main/user/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such column: main_user.middle_name

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/options.py", line 719, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 192, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/decorators.py", line 190, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/views/decorators/cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 234, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/admin/sites.py", line 207, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 251, in inner
    self._setup()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/utils/functional.py", line 404, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 40, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/middleware.py", line 20, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/__init__.py", line 311, in get_user
    user = backend.get_user(user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/contrib/auth/backends.py", line 232, in get_user
    user = UserModel._default_manager.get(pk=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 629, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 366, in __len__
    self._fetch_all()
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 1949, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1623, in execute_sql
    cursor.execute(sql, params)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/db/backends/sqlite3/base.py", line 360, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such column: main_user.middle_name
ERROR 2025-10-17 16:37:46,465 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 500 194608
INFO 2025-10-17 16:38:11,918 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 200 15423
INFO 2025-10-17 16:38:11,937 basehttp "GET /static/admin/css/base.css HTTP/1.1" 200 22120
INFO 2025-10-17 16:38:11,938 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2808
INFO 2025-10-17 16:38:11,939 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 200 1653
INFO 2025-10-17 16:38:11,939 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2025-10-17 16:38:11,940 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2025-10-17 16:38:11,944 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 200 6878
INFO 2025-10-17 16:38:11,944 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2025-10-17 16:38:11,945 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9777
INFO 2025-10-17 16:38:11,946 basehttp "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2025-10-17 16:38:11,947 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 16:38:11,947 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 200 8076
INFO 2025-10-17 16:38:11,949 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2025-10-17 16:38:11,949 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2025-10-17 16:38:11,950 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2025-10-17 16:38:11,951 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2025-10-17 16:38:11,951 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2025-10-17 16:38:11,953 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-17 16:38:11,986 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-10-17 16:38:12,000 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-10-17 16:38:12,001 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-10-17 16:38:12,001 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-10-17 16:38:12,047 basehttp "GET /favicon.ico HTTP/1.1" 200 68
INFO 2025-10-17 16:38:14,551 basehttp "GET /api/controller-panel/add-user/ HTTP/1.1" 200 59077
INFO 2025-10-17 16:38:19,789 basehttp "GET /api/controller-panel/add-user/?filter_role=&filter_group=1&filter_kafedra=&filter_bulim= HTTP/1.1" 200 15641
INFO 2025-10-17 16:38:49,298 basehttp "GET /api/controller-panel/add-user/?filter_role=&filter_group=1&filter_kafedra=&filter_bulim= HTTP/1.1" 200 15641
INFO 2025-10-17 16:38:51,432 basehttp "GET /api/controller-panel/download-student-import-template/ HTTP/1.1" 200 4948
INFO 2025-10-17 16:40:33,558 basehttp "GET /api/controller-panel/add-user/?filter_role=&filter_group=1&filter_kafedra=&filter_bulim= HTTP/1.1" 200 15619
INFO 2025-10-17 16:54:52,777 basehttp "GET /api/controller-panel/add-user/?filter_role=&filter_group=1&filter_kafedra=&filter_bulim= HTTP/1.1" 200 15619
INFO 2025-10-17 17:02:53,555 basehttp "GET /admin/main/user/ HTTP/1.1" 200 48878
INFO 2025-10-17 17:02:53,579 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,580 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,581 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,581 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,582 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,584 basehttp "GET /static/admin/css/changelists.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,585 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,586 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,586 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,589 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 17:02:53,590 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,621 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,626 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,626 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,627 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,628 basehttp "GET /static/admin/js/filters.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,632 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:53,674 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-10-17 17:02:53,687 basehttp "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2025-10-17 17:02:53,690 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-10-17 17:02:53,691 basehttp "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2025-10-17 17:02:53,691 basehttp "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2025-10-17 17:02:53,692 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-10-17 17:02:55,159 basehttp "GET /admin/main/user/163/change/ HTTP/1.1" 200 55644
INFO 2025-10-17 17:02:55,183 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,183 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,183 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,184 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,185 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,187 basehttp "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,187 basehttp "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,188 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 200 8525
INFO 2025-10-17 17:02:55,189 basehttp "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2025-10-17 17:02:55,189 basehttp "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2025-10-17 17:02:55,191 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 17:02:55,192 basehttp "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,193 basehttp "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,194 basehttp "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,194 basehttp "GET /static/admin/js/inlines.js HTTP/1.1" 200 15628
INFO 2025-10-17 17:02:55,196 basehttp "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,229 basehttp "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,229 basehttp "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,233 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:55,235 basehttp "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
INFO 2025-10-17 17:02:55,235 basehttp "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2025-10-17 17:02:55,239 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 200 11991
INFO 2025-10-17 17:02:55,277 basehttp "GET /static/admin/img/icon-no.svg HTTP/1.1" 200 560
INFO 2025-10-17 17:02:55,278 basehttp "GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
INFO 2025-10-17 17:02:55,278 basehttp "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2025-10-17 17:02:55,286 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2025-10-17 17:02:55,288 basehttp "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2025-10-17 17:02:55,289 basehttp "GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
INFO 2025-10-17 17:02:55,335 basehttp "GET /favicon.ico HTTP/1.1" 200 68
INFO 2025-10-17 17:02:55,345 basehttp "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
INFO 2025-10-17 17:02:55,345 basehttp "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
INFO 2025-10-17 17:02:56,853 basehttp "GET /admin/main/user/163/password/ HTTP/1.1" 200 14497
INFO 2025-10-17 17:02:56,875 basehttp "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,875 basehttp "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,876 basehttp "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,877 basehttp "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,878 basehttp "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,879 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,880 basehttp "GET /static/admin/css/unusable_password_field.css HTTP/1.1" 200 663
INFO 2025-10-17 17:02:56,880 basehttp "GET /static/admin/css/forms.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,880 basehttp "GET /static/admin/js/unusable_password_field.js HTTP/1.1" 200 1480
INFO 2025-10-17 17:02:56,891 basehttp "GET /static/admin/css/widgets.css HTTP/1.1" 304 0
INFO 2025-10-17 17:02:56,938 basehttp "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2025-10-17 17:02:59,671 basehttp "GET /admin/main/user/163/change/ HTTP/1.1" 200 55644
INFO 2025-10-17 17:02:59,694 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 17:03:00,102 basehttp "GET /admin/main/user/ HTTP/1.1" 200 48878
INFO 2025-10-17 17:03:00,129 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 17:03:00,426 basehttp "GET /admin/main/user/?q=ilxiom HTTP/1.1" 200 15423
INFO 2025-10-17 17:03:00,450 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 17:03:01,145 basehttp "GET /admin/main/user/ HTTP/1.1" 200 48878
INFO 2025-10-17 17:03:01,169 basehttp "GET /admin/jsi18n/ HTTP/1.1" 200 6253
INFO 2025-10-17 17:03:01,174 basehttp "GET /static/admin/css/responsive.css HTTP/1.1" 200 16565
INFO 2025-10-17 17:03:01,202 basehttp "GET /favicon.ico HTTP/1.1" 200 68
INFO 2025-10-17 17:03:01,612 basehttp "GET /admin/ HTTP/1.1" 200 17147
INFO 2025-10-17 17:03:01,970 basehttp "GET /api/controller-panel/add-user/ HTTP/1.1" 200 59055
INFO 2025-10-17 17:03:04,648 basehttp "GET /api/controller-panel/add-user/?filter_role=&filter_group=1&filter_kafedra=&filter_bulim= HTTP/1.1" 200 15619
INFO 2025-10-17 17:03:06,736 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 25345
INFO 2025-10-17 17:03:15,929 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-17 17:03:16,010 basehttp "GET /favicon.ico HTTP/1.1" 200 68
INFO 2025-10-18 11:24:20,548 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 11:24:23,774 basehttp "GET /api/login/?next=/api/controller-panel/dashboard/ HTTP/1.1" 200 7794
INFO 2025-10-18 11:24:23,789 basehttp "GET /static/login/login.css HTTP/1.1" 304 0
INFO 2025-10-18 11:24:23,790 basehttp "GET /static/login/login.js HTTP/1.1" 304 0
INFO 2025-10-18 11:24:23,839 basehttp "GET /static/main/1.png HTTP/1.1" 200 48202
INFO 2025-10-18 11:24:36,085 basehttp "POST /api/login/?next=/api/controller-panel/dashboard/ HTTP/1.1" 302 0
INFO 2025-10-18 11:24:36,142 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 25345
INFO 2025-10-18 11:24:49,418 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:25:00,584 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 25345
INFO 2025-10-18 11:25:31,391 basehttp "GET /api/controller-panel/participated-students/ HTTP/1.1" 200 252668
INFO 2025-10-18 11:25:39,680 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 25345
INFO 2025-10-18 11:25:47,428 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:25:50,960 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
ERROR 2025-10-18 11:25:57,015 log Internal Server Error: /api/test-api/export-subject/Dinshunoslilk/pdf/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view main.views_test_api.export_subject_results_pdf didn't return an HttpResponse object. It returned None instead.
ERROR 2025-10-18 11:25:57,016 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02 HTTP/1.1" 500 69682
INFO 2025-10-18 11:26:05,940 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:26:07,602 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
ERROR 2025-10-18 11:26:16,356 log Internal Server Error: /api/test-api/export-subject/Dinshunoslilk/pdf/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view main.views_test_api.export_subject_results_pdf didn't return an HttpResponse object. It returned None instead.
ERROR 2025-10-18 11:26:16,357 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 500 69886
INFO 2025-10-18 11:39:03,586 basehttp "GET /api/login/?next=/api/controller-panel/dashboard/ HTTP/1.1" 200 7794
INFO 2025-10-18 11:39:13,733 basehttp "POST /api/login/?next=/api/controller-panel/dashboard/ HTTP/1.1" 302 0
INFO 2025-10-18 11:39:13,747 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 25345
INFO 2025-10-18 11:39:23,764 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:39:35,445 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
ERROR 2025-10-18 11:39:45,552 log Internal Server Error: /api/test-api/export-subject/Dinshunoslilk/pdf/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view main.views_test_api.export_subject_results_pdf didn't return an HttpResponse object. It returned None instead.
ERROR 2025-10-18 11:39:45,552 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 500 69886
INFO 2025-10-18 11:42:34,312 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 11:42:34,736 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 11:42:39,230 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 11:42:39,550 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 11:43:12,059 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:43:21,904 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:43:24,268 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
ERROR 2025-10-18 11:43:29,359 log Internal Server Error: /api/test-api/export-subject/Dinshunoslilk/pdf/
ERROR 2025-10-18 11:43:29,359 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 500 30
INFO 2025-10-18 11:43:53,345 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 11:43:53,714 autoreload Watching for file changes with StatReloader
ERROR 2025-10-18 11:43:57,127 log Internal Server Error: /api/test-api/export-subject/Dinshunoslilk/pdf/
Traceback (most recent call last):
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/home/javodev/.local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view main.views_test_api.export_subject_results_pdf didn't return an HttpResponse object. It returned None instead.
ERROR 2025-10-18 11:43:57,128 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 500 69886
INFO 2025-10-18 11:47:03,976 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 11:47:04,351 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 11:48:02,571 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 200 9703
INFO 2025-10-18 11:48:24,322 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 10545697
INFO 2025-10-18 11:48:25,695 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 25345
INFO 2025-10-18 11:48:28,018 basehttp "GET /api/controller-panel/logout/ HTTP/1.1" 302 0
INFO 2025-10-18 11:48:28,029 basehttp "GET /api/login/ HTTP/1.1" 200 7794
INFO 2025-10-18 11:48:40,953 basehttp "POST /api/login/ HTTP/1.1" 302 0
INFO 2025-10-18 11:48:40,960 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 20302
INFO 2025-10-18 11:48:49,268 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 8761819
INFO 2025-10-18 11:48:54,602 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 11:48:59,557 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 200 8646
INFO 2025-10-18 11:49:46,728 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 11:49:51,386 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_03&semester=3 HTTP/1.1" 200 7840
INFO 2025-10-18 11:51:50,191 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 11:51:56,860 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02 HTTP/1.1" 200 8595
INFO 2025-10-18 11:56:19,657 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 11:56:20,059 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 11:56:50,158 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 8761819
INFO 2025-10-18 11:56:53,187 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 11:56:59,524 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02&semester=3 HTTP/1.1" 200 7999
INFO 2025-10-18 11:57:09,230 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 11:57:14,225 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_03&semester=3 HTTP/1.1" 200 7903
INFO 2025-10-18 11:59:18,276 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 11:59:18,657 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 12:00:22,749 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 12:00:23,097 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 12:02:42,231 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 12:02:42,598 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 12:03:20,420 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 12:03:20,790 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 12:03:28,493 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 8761819
INFO 2025-10-18 12:03:36,660 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 12:03:37,065 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 12:05:25,069 basehttp "GET /api/test-api/all-results/ HTTP/1.1" 200 8761819
INFO 2025-10-18 12:05:28,353 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 12:05:31,429 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_02 HTTP/1.1" 200 8131
INFO 2025-10-18 12:05:42,677 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 12:05:46,550 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=MTS_24_03 HTTP/1.1" 200 7913
INFO 2025-10-18 12:05:51,349 basehttp "GET /api/test-api/subject/Dinshunoslilk/groups/ HTTP/1.1" 200 45
INFO 2025-10-18 12:05:54,025 basehttp "GET /api/test-api/export-subject/Dinshunoslilk/pdf/?group=409 HTTP/1.1" 200 6438
INFO 2025-10-18 12:06:05,813 autoreload /home/javodev/Shaxobiddin/KatDPI_TEST/KatDPI_test/backend/main/views_test_api.py changed, reloading.
INFO 2025-10-18 12:06:06,175 autoreload Watching for file changes with StatReloader
INFO 2025-10-18 12:06:12,277 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 20302
INFO 2025-10-18 12:06:19,974 basehttp "GET /api/controller-panel/add-test/?target=student HTTP/1.1" 200 12190
INFO 2025-10-18 12:06:25,004 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 20302
INFO 2025-10-18 12:06:25,029 basehttp "GET /favicon.ico HTTP/1.1" 200 68
INFO 2025-10-18 12:06:31,004 basehttp "GET /api/controller-panel/add-test/?target=student HTTP/1.1" 200 12190
INFO 2025-10-18 12:06:31,030 basehttp "GET /favicon.ico HTTP/1.1" 200 68
INFO 2025-10-18 12:06:33,357 basehttp "GET /api/controller-panel/dashboard/ HTTP/1.1" 200 20302
